<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign up</name>
   <tag></tag>
   <elementGuidId>8bed83d1-72c8-4545-bc6b-280fbceb4b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/section/div/div[2]/div/div/div/div/div[3]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-impRdV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39694f76-1eb5-4d32-981f-12a4b8ba3432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-baseweb</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aac7459c-ae1c-4b33-bb52-bcccb3b543f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.uber.com/in/en/s/d/join/?exp=2021SUE_t1&amp;next_url=https%3A%2F%2Fdrivers.uber.com%2Fp3%2F&amp;source=auth%5C&amp;uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957</value>
      <webElementGuid>b4d66629-4ff8-432c-8ff4-51f750490067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sign up to become a Fleet partner</value>
      <webElementGuid>ffd779b0-ee6d-41cb-82a0-978c823fd151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>9b8edc5f-b098-45b3-8f79-ab4321661ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-name</name>
      <type>Main</type>
      <value>fleet-partners_5246e7e2-a5bd-4ad2-975f-f94140cb1a16_ctaOne.ctaDetails_cta1</value>
      <webElementGuid>9cac9047-22cb-4849-9053-b3087aa4e53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-impRdV</value>
      <webElementGuid>a2725a5b-4e28-4934-bc00-3e050fd8d0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uclick-id</name>
      <type>Main</type>
      <value>94d95b38-3e58-4cf5-8ed6-d3df3e6cb957</value>
      <webElementGuid>64d40a3d-4d60-4736-bd06-3cb79a7a524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-PKJb&quot;]/section[@class=&quot;css-dDHHCg&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-boCQJm&quot;]/div[@class=&quot;css-bVFrLX&quot;]/div[@class=&quot;css-iFQotK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-PKJb&quot;]/div[@class=&quot;css-WiLSj&quot;]/a[@class=&quot;css-impRdV&quot;]</value>
      <webElementGuid>7021a800-7d63-4534-bf03-1207f92b79a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div/div/div[3]/div/a</value>
      <webElementGuid>56abd016-e0d6-42fd-ada6-8e3558588cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up')]</value>
      <webElementGuid>7b4a58aa-3593-4487-9d07-c694016a027a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start your car-rental business with Uber'])[1]/following::a[1]</value>
      <webElementGuid>45d1231e-ec2b-48d8-adc5-e5b7d62fe92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results'])[2]/following::a[1]</value>
      <webElementGuid>bda07423-1706-4760-b1c0-1be34544d1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why become a Fleet partner'])[1]/preceding::a[1]</value>
      <webElementGuid>f673d767-05bf-4d4d-9dac-43daf66ebabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate attractive earnings'])[1]/preceding::a[1]</value>
      <webElementGuid>9f32b71f-6366-418a-942a-301a5dc2cfc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.uber.com/in/en/s/d/join/?exp=2021SUE_t1&amp;next_url=https%3A%2F%2Fdrivers.uber.com%2Fp3%2F&amp;source=auth%5C&amp;uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957')]</value>
      <webElementGuid>3fd947cb-b948-4ee4-817c-a3fe60b6a80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>66c9cf0f-93a4-41da-abaf-d35d8994e454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.uber.com/in/en/s/d/join/?exp=2021SUE_t1&amp;next_url=https%3A%2F%2Fdrivers.uber.com%2Fp3%2F&amp;source=auth%5C&amp;uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957' and (text() = 'Sign up' or . = 'Sign up')]</value>
      <webElementGuid>a242dfcb-7428-443d-8530-f9e66e2e8cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
