<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>570d5485-d2ad-46b9-bd88-15f6e8d5569a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.logo_head > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headers']/header/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce281eee-f2ca-419a-b197-7601aa814515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/irctc-new-logo.png</value>
      <webElementGuid>b655ee43-8c53-466e-b607-69ef03e0ef7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headers&quot;)/header[@class=&quot;main_header fixed_header&quot;]/div[@class=&quot;container clearfix&quot;]/div[@class=&quot;logo_head&quot;]/a[1]/img[1]</value>
      <webElementGuid>902c3ab8-c8a3-4922-a86a-57dd58c9050b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headers']/header/div/div/a/img</value>
      <webElementGuid>b128cac2-9bcb-46e1-a07f-76704a5aa0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>040f5533-a765-4665-9ee5-5bf7379ed216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/irctc-new-logo.png']</value>
      <webElementGuid>aab25ad3-eb34-4c80-a55d-21a53808a07b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
