<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Log In  Support_nav__logo-img</name>
   <tag></tag>
   <elementGuidId>c748a26b-b30f-4fbc-906b-4e0eb11bde50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.nav__logo-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mega-nav']/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>89a3fc56-f95b-4e06-a1c9-3be79b548b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav__logo-img</value>
      <webElementGuid>dc271afa-069b-48a7-acce-47391f118d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3abbb620-5ac2-455e-b2bc-ad98c9ebaa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/themes/custom/hansel/images/rs-logo-2021B.svg</value>
      <webElementGuid>26dcefb6-8cbf-43f5-b2f2-011667bb5ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rackspace Technology Logo</value>
      <webElementGuid>e3480db7-3c9b-4fd4-ab44-a7c5ca228806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mega-nav&quot;)/div[@class=&quot;nav__fluid--container&quot;]/div[@class=&quot;nav__base&quot;]/div[@class=&quot;nav__logo&quot;]/a[@class=&quot;nav__logo-link&quot;]/img[@class=&quot;nav__logo-img&quot;]</value>
      <webElementGuid>312669b5-5031-48f0-8697-a72a02357469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mega-nav']/div[2]/div/div/a/img</value>
      <webElementGuid>321c53b1-b535-4b56-9333-fb33f9fae499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rackspace Technology Logo']</value>
      <webElementGuid>5a1bc6f5-6bee-4f13-866c-3fb2eaf1d878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>79d51d9d-44e2-4835-9cc0-f7f1003222be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/themes/custom/hansel/images/rs-logo-2021B.svg' and @alt = 'Rackspace Technology Logo']</value>
      <webElementGuid>6de70551-2ca4-453b-8afe-2bc0842be41a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
