<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Solutions</name>
   <tag></tag>
   <elementGuidId>8aa07ce9-603e-4124-be4b-86496e31d8ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.nav__mega-mbl--linkText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mega-nav']/div[4]/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5c5e2fee-1be7-4f89-8fa9-c82acf924fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav__mega-mbl--linkText</value>
      <webElementGuid>74b65e93-e803-484d-a805-674ff75d0098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Solutions
          </value>
      <webElementGuid>520de8a6-4987-4caf-9442-9360bb85b6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mega-nav&quot;)/div[@class=&quot;nav__mega-mbl&quot;]/ul[@class=&quot;nav__mega-mbl--list&quot;]/li[@class=&quot;nav__mega-mbl--item&quot;]/a[@class=&quot;nav__mega-mbl--link&quot;]/span[@class=&quot;nav__mega-mbl--linkText&quot;]</value>
      <webElementGuid>d693b029-e41e-4d36-a0d9-cd4253aa5db3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mega-nav']/div[4]/ul/li/a/span</value>
      <webElementGuid>f93e2c1b-6dfb-4f7a-b4ac-e13919bfd1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Mobile Menu'])[1]/following::span[1]</value>
      <webElementGuid>484a6306-2ab9-4b4b-b2f0-e7156815b684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::span[2]</value>
      <webElementGuid>663442b0-3908-44c9-8c49-901ad7e179e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud'])[3]/preceding::span[1]</value>
      <webElementGuid>228fd5b1-efd5-4844-a536-20da28bd7bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Adoption and Migration'])[1]/preceding::span[2]</value>
      <webElementGuid>2baef63a-4e2a-4eaa-beff-01068ad0c64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a/span</value>
      <webElementGuid>6f9040f2-bae4-4e78-93ad-888e93de4307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            Solutions
          ' or . = '
            Solutions
          ')]</value>
      <webElementGuid>a0ffa9b9-55fb-4859-8bb5-8879513941f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
