<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Book your call</name>
   <tag></tag>
   <elementGuidId>8b193634-44d6-4df8-b8c2-c903e4aec003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gads-contact-hub-panel-1-headline > a.so-rpl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='gads-contact-hub-panel-1-headline']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db5e6bcc-8753-4b66-8a78-b3bdbb47a863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ads.google.com/intl/en_in/home/contact-us/schedule/?subid=ww-ww-et-g-awa-a-g_hpafoot1_1!o2</value>
      <webElementGuid>1279b52a-3f8b-46ed-8b79-3544ffc6ffd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Click to start scheduling a meeting. Mon–Fri, 9:00am–6:00pm IST</value>
      <webElementGuid>c717b182-373a-4db1-bb71-c8df16cb1d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-cta-name</name>
      <type>Main</type>
      <value>schedulemeeting</value>
      <webElementGuid>32381759-959b-4fa5-bf7f-42902771ccc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-module-name</name>
      <type>Main</type>
      <value>gads-contact-hub</value>
      <webElementGuid>7ef6050c-1ded-4721-9d1b-487f533d8994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>so-rpl</value>
      <webElementGuid>8e05827c-dd6c-4f7a-a0fe-463d16e4c9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                              Book your call
                            </value>
      <webElementGuid>392445f3-950d-4859-ab33-7b6e53af7c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gads-contact-hub-panel-1-headline&quot;)/a[@class=&quot;so-rpl&quot;]</value>
      <webElementGuid>7ea4afb6-76cd-4d9f-9307-0558d513290f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='gads-contact-hub-panel-1-headline']/a</value>
      <webElementGuid>a4af5f87-f42a-4b7c-a0ca-a06528c4dbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Book your call')]</value>
      <webElementGuid>bcfa801b-9876-462f-b7f4-67e11d082b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Help Centre'])[1]/following::a[1]</value>
      <webElementGuid>932556c0-94e8-47e3-8aab-7c3fb9d5537d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call 1800-572-8309'])[2]/preceding::a[1]</value>
      <webElementGuid>cda86faf-6363-494e-a071-226148fea3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Google Ads'])[1]/preceding::a[6]</value>
      <webElementGuid>1c760075-f9a7-4f91-b2fa-91d74b018eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book your call']/parent::*</value>
      <webElementGuid>511830ff-b800-4d90-8034-22e489e10d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://ads.google.com/intl/en_in/home/contact-us/schedule/?subid=ww-ww-et-g-awa-a-g_hpafoot1_1!o2')])[4]</value>
      <webElementGuid>cf8da295-dc69-46b6-85a6-f119ebf31a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>5823e2e3-e1ca-4e42-8f6a-172cad41f4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ads.google.com/intl/en_in/home/contact-us/schedule/?subid=ww-ww-et-g-awa-a-g_hpafoot1_1!o2' and (text() = '
                              Book your call
                            ' or . = '
                              Book your call
                            ')]</value>
      <webElementGuid>229c213e-5e19-4fac-9724-085e50f02bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
