<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Public Inbox</name>
   <tag></tag>
   <elementGuidId>837be93e-c195-4caa-8df7-f0d370ee8816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.inbox-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='site-header']/div/div/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0212960-dc10-4ccc-acf2-f91b6ea88476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inbox-link</value>
      <webElementGuid>2e984734-9ef2-4670-af40-5f6018341a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mailinator.com/v4/public/inboxes.jsp</value>
      <webElementGuid>f764ec39-47c4-4688-909c-2ed5b2c7bce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Public Inbox</value>
      <webElementGuid>3a572985-0b04-491f-aa97-a8e546ff81ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;g5core-top-bar g5core-top-bar-desktop&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;g5core-top-bar-inner&quot;]/div[@class=&quot;g5core-top-bar-right&quot;]/div[@class=&quot;g5core-top-bar-item g5core-tbi-custom-html-2&quot;]/a[@class=&quot;inbox-link&quot;]</value>
      <webElementGuid>650c6480-3bf2-4b01-b19a-48b641dfabf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='site-header']/div/div/div/div[2]/div/a</value>
      <webElementGuid>8d4de19b-1e7e-485e-a219-6777ebf46662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Public Inbox')]</value>
      <webElementGuid>ce4fe6a2-4980-46c3-9923-1ddd8ddaf672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[1]/following::a[1]</value>
      <webElementGuid>4c760bd8-5d9e-4fd3-8bdf-584f792f7d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Mailinator'])[1]/preceding::a[2]</value>
      <webElementGuid>6b2aa6fe-9ca1-4613-85d7-21688d74c2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications/Solutions'])[1]/preceding::a[3]</value>
      <webElementGuid>21121d82-26dc-45f6-8788-ebb08d806194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Public Inbox']/parent::*</value>
      <webElementGuid>f1608943-4d5b-478e-ab0c-a3fe9f71f56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mailinator.com/v4/public/inboxes.jsp')]</value>
      <webElementGuid>fabb2626-4ed2-45fc-866b-f8d59cb42bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>53dc6588-4eb2-435e-b1e4-1638529f7cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mailinator.com/v4/public/inboxes.jsp' and (text() = 'Public Inbox' or . = 'Public Inbox')]</value>
      <webElementGuid>b333cbd2-b46a-4e7f-b44f-8af75052f2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
