<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JioMart</name>
   <tag></tag>
   <elementGuidId>c475c17a-ca8e-4732-8259-97cf56925f4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[2]/div/div/div/div[2]/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b2b728d-df8f-4f22-851f-cde8fe57fef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>reliance-jiomart.html</value>
      <webElementGuid>366a8a41-6223-4997-9aa9-b422d8acb330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JioMart</value>
      <webElementGuid>b0b9e067-2fbb-42e2-bcf9-619578073718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[@class=&quot;active&quot;]/div[@class=&quot;megamenu none&quot;]/div[@class=&quot;megamenu-row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col2&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[5]/a[1]</value>
      <webElementGuid>f88349a2-a70a-4984-8848-d64f4628460f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[2]/div/div/div/div[2]/ul/li[5]/a</value>
      <webElementGuid>cb857d1a-dfff-4f41-985a-ee197a1e6286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JioMart')]</value>
      <webElementGuid>751cb3b7-8495-4c5e-b996-b5c630145abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reliance Smart Point'])[1]/following::a[1]</value>
      <webElementGuid>067fc074-2aa3-463a-bc08-e492a7b974cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reliance Smart'])[1]/following::a[2]</value>
      <webElementGuid>f626e961-c2a8-4321-9c11-3fd64f30ec00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reliance Digital'])[1]/preceding::a[1]</value>
      <webElementGuid>d6cd9be2-1d05-48d9-9280-220bb66b3376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JioMart Digital'])[1]/preceding::a[2]</value>
      <webElementGuid>54f0ab0d-777a-49a4-9369-8968be97e0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JioMart']/parent::*</value>
      <webElementGuid>b08e4e5b-11a6-483f-a237-df59ef566b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'reliance-jiomart.html')]</value>
      <webElementGuid>210bb84c-9a25-4412-ba19-b79dd451bef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>734f6288-4efe-4eda-b9b1-40ee67476a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'reliance-jiomart.html' and (text() = 'JioMart' or . = 'JioMart')]</value>
      <webElementGuid>43433ddd-3d8e-4c60-a64c-655a5da341c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
