<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Store Locator</name>
   <tag></tag>
   <elementGuidId>5138a7b8-cdab-411d-a5ca-d884676729ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-icon.cart-info > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e520dca7-fd70-4896-9f9d-a57f3bd87aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://storelocator.ril.com/Retail.aspx</value>
      <webElementGuid>cb79f056-b76b-4371-9227-5e46b808f6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f908ea5b-f498-4623-90d4-413ef796f5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Store Locator </value>
      <webElementGuid>89dd8fdd-89b6-427c-a95a-b31e30c77231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/li[@class=&quot;nav-icon cart-info&quot;]/a[1]</value>
      <webElementGuid>57d9a8e0-b927-44cc-ab5d-3fd26cdb61bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[6]/a</value>
      <webElementGuid>a4b2b408-951c-4a1b-95a3-2454e075ac73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Store Locator')]</value>
      <webElementGuid>11a42044-e7a8-43df-aae8-a47f71c95c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RBL Careers'])[1]/following::a[1]</value>
      <webElementGuid>07a6ab36-8f85-4b81-8c29-55c3b9b6420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Now'])[1]/following::a[2]</value>
      <webElementGuid>afd8dfd4-1775-4140-8f54-e2638517b380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer First'])[1]/preceding::a[1]</value>
      <webElementGuid>82cc2cec-32f0-44e4-af2d-45b6488ac205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Building India', &quot;'&quot;, 's largest retail company')])[1]/preceding::a[1]</value>
      <webElementGuid>360091c9-d00b-4ff7-babf-f9a744f608c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Store Locator']/parent::*</value>
      <webElementGuid>b5a0b2b0-51e1-4748-b5bd-6725a704ebb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://storelocator.ril.com/Retail.aspx']</value>
      <webElementGuid>61865e4a-ff32-48ac-a6f0-9579fc8944f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>d719350e-9cd2-41b6-a9cf-8cf71f7ffee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://storelocator.ril.com/Retail.aspx' and (text() = 'Store Locator ' or . = 'Store Locator ')]</value>
      <webElementGuid>dda719fa-ecf1-4c6c-87d5-5047d541aa11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
