<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Netmeds_img-responsive</name>
   <tag></tag>
   <elementGuidId>df3bf020-7ace-4701-be43-6e10c57ea460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='page-content']/div/div/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.b-logos > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cec3c5eb-55e3-4404-99a7-053201ba57ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/brands/larg/jio-mart-logo.jpg</value>
      <webElementGuid>1985356d-6028-4eca-a7cb-b0bb6faee2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>6a1544d7-9d20-4d3c-bae6-a0b4f344cc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;b-logos&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>85815546-5183-49f4-9ab3-6c020c9b6985</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='page-content']/div/div/div[2]/div/img</value>
      <webElementGuid>fffdcd09-fe86-4996-bbd0-a6f5469d1434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>291ab07c-9ff3-4bad-99e6-f92ccb2640ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/brands/larg/jio-mart-logo.jpg']</value>
      <webElementGuid>c3c82607-8e1a-48e3-98cd-dd016547ae46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
