<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Book your journey now with the worlds la_24b2db</name>
   <tag></tag>
   <elementGuidId>5688984d-9e6b-4019-8ee8-863afa55cb92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.hero-tag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rdc-root']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>45dd0631-6122-4a68-804c-2c365c5916c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero-tag</value>
      <webElementGuid>47cb059f-8ca1-4539-b9c4-524ca7e919eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book your journey now with the world's largest bus platform</value>
      <webElementGuid>72ce9273-2936-49e6-a1b8-897ba24e66a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdc-root&quot;)/div[1]/div[@class=&quot;hero-wrapper&quot;]/div[@class=&quot;hero-tag-cont&quot;]/h1[@class=&quot;hero-tag&quot;]</value>
      <webElementGuid>607b5d96-1c38-47ae-b4f1-3ff2edb261fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdc-root']/div/div/div/h1</value>
      <webElementGuid>56491299-f8cb-46e0-84eb-b2de41785eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STAY HERE'])[1]/following::h1[1]</value>
      <webElementGuid>9901a9ca-7a53-4838-956c-6f7e56ea0919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROCEED'])[1]/following::h1[1]</value>
      <webElementGuid>8cfe6734-d117-4189-95ae-8e2ecafa52e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='source'])[1]/preceding::h1[1]</value>
      <webElementGuid>bf8b809b-05dd-42c4-a953-382d2943a3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='destination'])[1]/preceding::h1[1]</value>
      <webElementGuid>34139cb0-4c3e-4273-9716-a5e2b0052d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f1389e9d-0043-40be-a650-66c0ce27f835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = concat(&quot;Book your journey now with the world&quot; , &quot;'&quot; , &quot;s largest bus platform&quot;) or . = concat(&quot;Book your journey now with the world&quot; , &quot;'&quot; , &quot;s largest bus platform&quot;))]</value>
      <webElementGuid>5a270760-4fe6-4aa8-b13c-22f6b5a07c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
