<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Yahoo Home__yb_hd8j6 _yb_typq8</name>
   <tag></tag>
   <elementGuidId>de63210e-ed38-4a8c-abe0-65ee4b448693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img._yb_hd8j6._yb_typq8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ybar-logo']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc6ad5aa-f714-4868-850c-5e7fcac80d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_yb_hd8j6 _yb_typq8</value>
      <webElementGuid>fc448923-85ef-4155-ad55-8e33928c320d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s.yimg.com/rz/p/yahoo_homepage_en-US_s_f_p_bestfit_homepage.png</value>
      <webElementGuid>2132f65e-4166-46a8-ac0c-9e4a531473fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://s.yimg.com/rz/p/yahoo_homepage_en-US_s_f_p_bestfit_homepage.png 1x, https://s.yimg.com/rz/p/yahoo_homepage_en-US_s_f_p_bestfit_homepage_2x.png 2x</value>
      <webElementGuid>7686fb72-5a71-45f1-af16-5ee40a9af0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34b261d9-1a0a-4428-b22b-56ba3ae3bf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-logo&quot;)/img[@class=&quot;_yb_hd8j6 _yb_typq8&quot;]</value>
      <webElementGuid>4bfc7d0e-b839-4d17-880e-22ead7bc8658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ybar-logo']/img</value>
      <webElementGuid>beeef7ca-3a01-4055-bfe7-535d6e7edbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s.yimg.com/rz/p/yahoo_homepage_en-US_s_f_p_bestfit_homepage.png')]</value>
      <webElementGuid>10bbe564-6d2f-4db1-a6be-d0fe377dd033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>99fb267a-5fb6-4c89-b38b-45f9ce55aeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s.yimg.com/rz/p/yahoo_homepage_en-US_s_f_p_bestfit_homepage.png']</value>
      <webElementGuid>8350c288-ef83-4f21-b938-ab7b43cf8715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
