<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Vehicles</name>
   <tag></tag>
   <elementGuidId>e7591031-185a-4291-908c-0517696d217a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#brand-nav-vm-av-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='brand-nav-vm-av-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>768cdb5e-4b13-4f3a-810c-e3ec284c660b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-item flyout-toggle fgx-btn fgx-brand-container-pad-mbl</value>
      <webElementGuid>a86e19ca-4ea1-44e1-8707-417f7f868b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01d41315-b272-4a10-af2b-96c130e97de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>brand-nav-vm-av-btn</value>
      <webElementGuid>34b3445c-7233-4e46-a0e2-fa990a29e061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flyout-type</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>99c3a23f-7d24-4793-b76a-d93e62abcd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>brand-nav-vm-av-cnt</value>
      <webElementGuid>4d217caa-21a8-4284-a812-44a43d90f969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fgx-fordmainnav-flyout-id</name>
      <type>Main</type>
      <value>fgx-fordMainNav-flyout-1</value>
      <webElementGuid>d59f0d1d-100f-4058-b8bb-1b91f81778f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Vehicles</value>
      <webElementGuid>fc82796d-aa3e-4b91-a103-132d0d9f75c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand-nav-vm-av-btn&quot;)</value>
      <webElementGuid>057dab61-9861-4f3e-aef2-de8b504ca33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='brand-nav-vm-av-btn']</value>
      <webElementGuid>3cc62557-ae1c-455e-bc4b-60251212a02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='brand-nav-vm-av-item']/button</value>
      <webElementGuid>d42db610-cc2f-4104-aa1b-8e4a9da5b772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close menu'])[2]/following::button[1]</value>
      <webElementGuid>74e155b6-7d0a-420b-ba05-04bf5893ba6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close menu'])[1]/following::button[2]</value>
      <webElementGuid>9ffd8d49-6c10-4921-b460-f32c76c0174e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUVs &amp; Cars'])[1]/preceding::button[1]</value>
      <webElementGuid>a4c227c9-84a9-4154-977b-3c4722b8dcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>63a9f4af-38ed-4a21-8cf6-95855f63b231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'brand-nav-vm-av-btn' and (text() = '
                                        Vehicles' or . = '
                                        Vehicles')]</value>
      <webElementGuid>3c08d988-403f-46fe-86d2-62b543b0f1b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
