<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign up_high-res-image</name>
   <tag></tag>
   <elementGuidId>4199d8e7-cd74-4222-bcc4-53225b33db8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-gJqsIT.bdDCMj.logo > img.high-res-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d342bd45-2225-4574-99a4-c68fb38176d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://b.zmtcdn.com/web_assets/8313a97515fcb0447d2d77c276532a511583262271.png</value>
      <webElementGuid>73ec3d9d-232a-44ee-b317-33f68e1a945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>high-res-image</value>
      <webElementGuid>ed4fb86f-8d40-441f-82ec-6066f54f777b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>cf813f79-1a90-42f9-9399-d54829e10ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fEUNkw gAkuDn&quot;]/div[@class=&quot;sc-bIqbHp kPxRJH&quot;]/div[@class=&quot;contents-wrapper&quot;]/div[@class=&quot;sc-gJqsIT bdDCMj logo&quot;]/img[@class=&quot;high-res-image&quot;]</value>
      <webElementGuid>06cfbad8-c38c-477c-8037-6d6c801edfe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/img</value>
      <webElementGuid>d68a095f-3c3f-4e55-bbab-44d9f34f9ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://b.zmtcdn.com/web_assets/8313a97515fcb0447d2d77c276532a511583262271.png')]</value>
      <webElementGuid>82e74615-149f-4c78-870a-7cc0b63a7fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>2d6d11b5-b166-4e37-aaeb-f9ce62305c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://b.zmtcdn.com/web_assets/8313a97515fcb0447d2d77c276532a511583262271.png']</value>
      <webElementGuid>30319d6e-2696-4c87-ba3a-a5b92eba5d6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
