<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Restaurants Near Me</name>
   <tag></tag>
   <elementGuidId>c3972c3c-97d8-4688-bfb9-d2e49fb56c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/table/tbody/tr/td/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.l</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f88107be-4fbe-4102-835d-4eb9c3435091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>977d9a73-4eba-4586-83c1-8bd3dfa9b7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.swiggy.com/restaurants-near-me</value>
      <webElementGuid>34997126-1842-4971-a442-9f3c8a3b7574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwiDsb61s7uBAxWLxjgGHYCxB0MQjBB6BAgQEAE</value>
      <webElementGuid>39b54b14-24a8-4d71-b228-c47d822fa67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ping</name>
      <type>Main</type>
      <value>/url?sa=t&amp;source=web&amp;rct=j&amp;opi=89978449&amp;url=https://www.swiggy.com/restaurants-near-me&amp;ved=2ahUKEwiDsb61s7uBAxWLxjgGHYCxB0MQjBB6BAgQEAE</value>
      <webElementGuid>2fd4f01b-6db4-4a78-8e8b-3a9e00f710cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Restaurants Near Me</value>
      <webElementGuid>4fe0d963-064a-4a3b-b34f-02f057cddf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;MjjYud&quot;]/div[@class=&quot;g&quot;]/div[@class=&quot;BYM4Nd&quot;]/table[@class=&quot;jmjoTe&quot;]/tbody[1]/tr[@class=&quot;mslg dmenKe&quot;]/td[@class=&quot;cIkxbf&quot;]/div[@class=&quot;usJj9c&quot;]/h3[1]/a[@class=&quot;l&quot;]</value>
      <webElementGuid>135b3f32-9898-4a12-9352-4f1530c221b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/table/tbody/tr/td/div/h3/a</value>
      <webElementGuid>057f9453-ed98-4507-b223-a8b587ba114f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Restaurants Near Me')]</value>
      <webElementGuid>9c625831-f882-4b9e-866d-a85271a8686f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.swiggy.com'])[2]/following::a[1]</value>
      <webElementGuid>fb9d03d9-2e9c-4f07-aae4-aa3033bb7bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swiggy'])[3]/following::a[1]</value>
      <webElementGuid>0c0cec4e-b05b-4ff1-bd73-5c45a80769d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find The Restaurants Serving Near Your Location. View ...'])[1]/preceding::a[1]</value>
      <webElementGuid>bd804eed-0b65-4fb1-a10a-dae156a09700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swiggy Instamart'])[1]/preceding::a[1]</value>
      <webElementGuid>994d96d0-5b6e-4310-9ceb-cd1c20f13722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Restaurants Near Me']/parent::*</value>
      <webElementGuid>3292db0e-6e9c-46f5-825e-bcc173463ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.swiggy.com/restaurants-near-me')]</value>
      <webElementGuid>f1633058-85cf-4e43-93ee-f233c0e2e1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>ed98356d-e3ca-4b65-9366-b0b7031e73ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.swiggy.com/restaurants-near-me' and (text() = 'Restaurants Near Me' or . = 'Restaurants Near Me')]</value>
      <webElementGuid>0186082e-60a8-4408-97da-0ed897e12350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
