<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Best offers for you</name>
   <tag></tag>
   <elementGuidId>bef64235-a074-4d11-bba0-833c367a890b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-dtInlm.evfMxD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='seo-core-layout']/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65c69e90-3ab0-47c0-93e0-305430ef9ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dtInlm evfMxD</value>
      <webElementGuid>30117c9e-e1f6-4631-8c47-8b5f2d3ba0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Best offers for you</value>
      <webElementGuid>f24eed48-fb76-41df-81e7-1c5139b21f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seo-core-layout&quot;)/div[@class=&quot;sc-cgjDci sc-gvPdwL jVa-dKa dpQwAI&quot;]/div[1]/div[@class=&quot;sc-lmUcrn bHaWiL&quot;]/div[@class=&quot;sc-dtBdUo jwwwLI&quot;]/div[@class=&quot;sc-dtInlm evfMxD&quot;]</value>
      <webElementGuid>f38a7ddf-5645-4e54-818d-b92ef3e0d90a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='seo-core-layout']/div/div/div/div[2]/div</value>
      <webElementGuid>fabb3da2-2162-4ff3-8ccb-36657a2f0536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[11]</value>
      <webElementGuid>b45697d1-e25e-4874-b29c-1a148233ef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[1]/following::div[12]</value>
      <webElementGuid>1353ed9a-8cdd-48c9-b35f-5f9295d42117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's on your mind?')])[1]/preceding::div[25]</value>
      <webElementGuid>56ab55cc-adbd-44e9-ba9a-a04873cfeeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>eb35a746-2444-4dd0-ba18-c5adc4275aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Best offers for you' or . = 'Best offers for you')]</value>
      <webElementGuid>a6c4cc1e-4cdc-4054-951f-2381b8c2038e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
