<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unexpected guests</name>
   <tag></tag>
   <elementGuidId>8be17307-eaa3-41f0-937a-19dd69ed5124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._2sbfu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/h1/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26b0ddd1-31db-4635-9852-fe5086b205c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2sbfu</value>
      <webElementGuid>fbf06334-ef9e-4ece-b6e3-ebbecf70c8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unexpected guests?</value>
      <webElementGuid>17737a37-3a91-48e7-9b44-51e932be261e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/div[@class=&quot;nDVxx&quot;]/div[@class=&quot;_1MdYR&quot;]/div[@class=&quot;_1TWur&quot;]/div[@class=&quot;_2COmU&quot;]/div[@class=&quot;m3-34&quot;]/h1[@class=&quot;sZsUd _2pZOT&quot;]/div[@class=&quot;_2sbfu&quot;]</value>
      <webElementGuid>b1b49c0a-3c04-483a-b909-d21b89ad4833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/h1/div[2]</value>
      <webElementGuid>4797b593-1446-4991-8cf9-f0ca17449874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hungry?'])[1]/following::div[1]</value>
      <webElementGuid>d6fcca9b-3b2d-4b70-9099-b4b776ec9b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/following::div[2]</value>
      <webElementGuid>78e9e8c7-6270-44f9-ba34-554426f72bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order food from favourite restaurants near you.'])[1]/preceding::div[1]</value>
      <webElementGuid>3a815c94-20a3-41be-a076-178de20cacda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locate Me'])[1]/preceding::div[3]</value>
      <webElementGuid>53c498f4-8e83-49b4-acc6-881e746783b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unexpected guests?']/parent::*</value>
      <webElementGuid>40063886-bb25-4f3d-9dda-9e08e2b43918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/div[2]</value>
      <webElementGuid>69e78d87-c8c1-48f3-9cf9-b7936462b0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Unexpected guests?' or . = 'Unexpected guests?')]</value>
      <webElementGuid>5b83a86e-155a-4de0-a0cf-c2ffca774031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
