<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in with QR code</name>
   <tag></tag>
   <elementGuidId>43d4dc9d-6ec0-415f-b262-b1d2d1a329b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='open-qr-code-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#open-qr-code-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2af833f1-26f5-42ab-82bc-47f4c621d7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-baseweb</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bef95b2c-f4ce-4cad-b1bd-7b98988e5cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>open-qr-code-btn</value>
      <webElementGuid>192f67b9-aad5-4a1d-aceb-417b5dcb93e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>qr-code-button</value>
      <webElementGuid>e11bded7-2dce-4c18-9c11-533ea405cdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e0 bc ak aw e1 e2 e3 e4 e5 e6 e7 e8 bu cm dh e9 ea eb ec bh co ed cq ee ef eg eh ei bw cn ck ej ek el em en eo ep bj b9 eq er es</value>
      <webElementGuid>c1954ec2-d597-4449-a454-67d01c5b31ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in with QR code</value>
      <webElementGuid>37be84cd-3990-4582-bf29-98947a1de4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;open-qr-code-btn&quot;)</value>
      <webElementGuid>b5b8b6d7-55a8-40b4-88f8-67ef84c0b130</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='open-qr-code-btn']</value>
      <webElementGuid>a4291bf2-68f8-4667-840a-f64f3bfa4488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div/div/div[2]/div[6]/div[3]/button</value>
      <webElementGuid>c0939c8a-082c-45e5-ae50-ed15faf3114a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changed your mobile number?'])[1]/following::button[4]</value>
      <webElementGuid>c27cfed1-5df9-4acb-a738-05e96d8f9267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::button[5]</value>
      <webElementGuid>a22d0c77-030b-4304-bb76-0218d246cc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::button[1]</value>
      <webElementGuid>ff859c81-b174-4546-8d22-67eebe1786e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/button</value>
      <webElementGuid>302e7d0f-7703-48ec-b8b6-c4ef9f585424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'open-qr-code-btn' and (text() = 'Log in with QR code' or . = 'Log in with QR code')]</value>
      <webElementGuid>87fb123a-e978-473b-9cdf-105fc0028cd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
