<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>eb901488-3686-4f16-aed9-f03ed484a9eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>585b40f3-5975-4ba8-b9e5-c80e2c4fdb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/setprefs?sig=0_tQRkZr-z5J9U6EWFjCWafEKQz4U%3D&amp;hl=bn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiFwt6GzLuBAxV-QjABHX13BmYQ2ZgBCBI</value>
      <webElementGuid>d52636f3-493c-4b76-9b52-5f5192225de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>বাংলা</value>
      <webElementGuid>69b0ff9d-ee12-48a6-9b97-346325a3f5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[2]</value>
      <webElementGuid>f842b5bd-8aa6-4776-bb83-8db07f61ffd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[2]</value>
      <webElementGuid>84012df4-4ab8-42dd-b85c-b1726f7ec4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'বাংলা')]</value>
      <webElementGuid>50c971fc-3b6f-4543-999c-8a6009abd83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='हिन्दी'])[1]/following::a[1]</value>
      <webElementGuid>84f935cd-5ed8-420d-887f-c8eaece86d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/preceding::a[1]</value>
      <webElementGuid>a2c87b8a-bd4f-4980-bffe-3f1a29335c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/preceding::a[2]</value>
      <webElementGuid>9e7ab397-4a40-43e5-b21b-a6cec0c36127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='বাংলা']/parent::*</value>
      <webElementGuid>81887e4d-e023-427f-9723-231426d5587b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/setprefs?sig=0_tQRkZr-z5J9U6EWFjCWafEKQz4U%3D&amp;hl=bn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiFwt6GzLuBAxV-QjABHX13BmYQ2ZgBCBI')]</value>
      <webElementGuid>02a98db2-158f-4835-b495-e7bbc2257109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>dc73605e-cae6-46dc-8d5a-4ea3107d3b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/setprefs?sig=0_tQRkZr-z5J9U6EWFjCWafEKQz4U%3D&amp;hl=bn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiFwt6GzLuBAxV-QjABHX13BmYQ2ZgBCBI' and (text() = 'বাংলা' or . = 'বাংলা')]</value>
      <webElementGuid>9ce31aab-e65e-4627-a89d-38eb05ecd51d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
