<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>eb901488-3686-4f16-aed9-f03ed484a9eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2de15bfc-3265-45d6-9ea5-3d476286a5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/setprefs?sig=0_qNmSuv5BCLsKon-g_NAiP4i7SdA%3D&amp;hl=hi&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjv2unn57OBAxXiTTABHZkFAAsQ2ZgBCBE</value>
      <webElementGuid>8344c8f5-4da7-41e8-a5bf-26765a37ef8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>हिन्दी</value>
      <webElementGuid>548babce-29d6-488b-afa7-43f47f3ff081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>45ed5a05-c523-4b91-8786-a0ffc33d5fb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>a30bfe1b-1fe2-4969-a8e1-0b0090fb10f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'हिन्दी')]</value>
      <webElementGuid>c45410bc-4942-472d-a694-8cfb27a32535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::a[2]</value>
      <webElementGuid>452cdc85-28ca-4390-9807-4afdf5275eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/preceding::a[1]</value>
      <webElementGuid>7b3ac59d-b43e-443c-8d6e-c94849240bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/preceding::a[2]</value>
      <webElementGuid>2fd90008-3146-48c6-b089-1bdcc151e38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='हिन्दी']/parent::*</value>
      <webElementGuid>a73261d6-c5b6-4f05-b921-cc3cf46f64a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/setprefs?sig=0_qNmSuv5BCLsKon-g_NAiP4i7SdA%3D&amp;hl=hi&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjv2unn57OBAxXiTTABHZkFAAsQ2ZgBCBE')]</value>
      <webElementGuid>7d5e591a-56f6-4653-8b4b-f050e26ded76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>2073ad4f-b20b-44d5-9a7f-483e9e1a88ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/setprefs?sig=0_qNmSuv5BCLsKon-g_NAiP4i7SdA%3D&amp;hl=hi&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjv2unn57OBAxXiTTABHZkFAAsQ2ZgBCBE' and (text() = 'हिन्दी' or . = 'हिन्दी')]</value>
      <webElementGuid>79f70eaf-cad3-4fdb-8f92-b20310e6e234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
