<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Images_gb_d</name>
   <tag></tag>
   <elementGuidId>11a2faa1-e03f-4138-a5f2-5430dabaa1ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gb_d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gbwa']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>634d547f-519c-49f8-8b32-b95e901f68bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_d</value>
      <webElementGuid>50eaffa0-e155-46de-83c1-6a9f7abc93c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Google apps</value>
      <webElementGuid>f9d1bcf1-c55d-49a4-b2a6-688feb11367b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/intl/en/about/products</value>
      <webElementGuid>b7437381-e891-4273-bc8d-d1bea8305296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a42e1e7-040f-4022-989e-4a0ec5d0ba6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da92b5dd-c5e6-4964-bb58-eb4a57f27145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>242e33d3-205d-4d27-be06-8668be8c3ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gbwa&quot;)/div[@class=&quot;gb_g&quot;]/a[@class=&quot;gb_d&quot;]</value>
      <webElementGuid>b61a9afc-1fa4-4ec6-be25-49e20c72c1ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gbwa']/div/a</value>
      <webElementGuid>22ec12f4-d269-47df-ad20-b9507e7d7f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/following::a[1]</value>
      <webElementGuid>d74cf700-3fb3-4e51-8bd2-3f9dc0c47245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::a[2]</value>
      <webElementGuid>f3bf46b8-c519-4d4a-ac3b-b5db66d68781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>a305e40b-2f0c-4729-b1fc-696ea7aa4cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[2]</value>
      <webElementGuid>d7da094e-8135-4070-849d-9b10a54eeea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/intl/en/about/products')]</value>
      <webElementGuid>96603205-c3da-4b6e-9683-0154527e6ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>1bc3d38f-0a79-43da-b87a-5d34cdc8db71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/intl/en/about/products']</value>
      <webElementGuid>7302023e-3cc4-4b31-8610-905c7904f736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
