<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_weather</name>
   <tag></tag>
   <elementGuidId>0f97ab22-02a7-4d8f-b51f-b166ab162536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mus_il_t.mus_tt8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jZ2SBf']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c761741c-f7fb-40f5-aec9-9b4f0d28dd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mus_il_t mus_tt8</value>
      <webElementGuid>daac06e6-9eee-4ba4-9f05-7f5d948f71c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>weather</value>
      <webElementGuid>ffc2f767-064d-4ed6-a7d5-1a486b4fc4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jZ2SBf&quot;)/div[@class=&quot;wM6W7d s2Wjec mus_pc&quot;]/div[@class=&quot;mus_il&quot;]/span[@class=&quot;mus_il_t mus_tt8&quot;]</value>
      <webElementGuid>61b7ad39-def3-4813-9fce-d734b4624578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jZ2SBf']/div/div/span</value>
      <webElementGuid>bf77500d-5406-4536-8bab-c52a041925a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::span[11]</value>
      <webElementGuid>d4072941-4fc0-42d3-8907-936dcf165ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::span[11]</value>
      <webElementGuid>3900dd49-8d05-494c-919c-ecc38505d460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri – Nashik, Maharashtra'])[1]/preceding::span[2]</value>
      <webElementGuid>da8d81ca-081a-4857-8061-6429f5fc6884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[4]</value>
      <webElementGuid>1e51dfca-7e1c-4412-a9fb-2e3e83e04850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='weather']/parent::*</value>
      <webElementGuid>a44cda9f-1afb-4764-b01b-5ff360169302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>b59bd5d4-aac2-47e4-9ddb-1bf763397226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'weather' or . = 'weather')]</value>
      <webElementGuid>a3c7b526-b608-4b6e-833d-106010feb655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
