<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get started</name>
   <tag></tag>
   <elementGuidId>a79c00af-7854-4b85-81c9-cdd457ce122e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-hKOqI > div.tab-content.css-cMSTid.css-PKJb > div.css-jHBTin.css-PKJb > div.css-PKJb > div.css-bAErhM > a.css-impRdV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfe0735c-560a-44da-9ef0-f419bebd6c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-baseweb</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6753a5bc-cb4a-4450-9979-1ab1133118b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.uber.com/in/en/drive/vehicle-solutions/fleet-partners/?uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957</value>
      <webElementGuid>5433c9f7-ab93-4d7b-a202-4afcae71ed73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Get started </value>
      <webElementGuid>64dd053a-78fb-4e37-88e8-ddd2be069e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started </value>
      <webElementGuid>c93ed4a0-f2a1-4937-9824-c93cdd6e548d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94cf60a5-03ac-4a1a-8820-cec8f61e9cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-name</name>
      <type>Main</type>
      <value>homepage_1ec73174-7956-4849-aae3-42b3887bfb87_items[2].content.buttons[0]_cta5</value>
      <webElementGuid>f9811a5f-5cf0-4e09-bb2c-bcd58d58ddb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-impRdV</value>
      <webElementGuid>a288b190-7f62-4b96-b75a-3d3b75f3ad05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uclick-id</name>
      <type>Main</type>
      <value>94d95b38-3e58-4cf5-8ed6-d3df3e6cb957</value>
      <webElementGuid>ba4e9068-f705-47bc-b4ef-9f0a5c2d081f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-gqcHgx&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-fVLpfI&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-hKOqI&quot;]/div[@class=&quot;tab-content css-cMSTid css-PKJb&quot;]/div[@class=&quot;css-jHBTin css-PKJb&quot;]/div[@class=&quot;css-PKJb&quot;]/div[@class=&quot;css-bAErhM&quot;]/a[@class=&quot;css-impRdV&quot;]</value>
      <webElementGuid>11f0036e-0129-4649-a729-83e8bd43ccc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>b71db698-1190-4ad0-bb0f-0ddc3813ba98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div[3]/div/div/div[2]/div/a</value>
      <webElementGuid>8c7ec0ec-807d-4c04-9efe-35f2024695dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get started')]</value>
      <webElementGuid>23522c27-dc37-468f-85f9-56f57700de12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make money by renting out your car'])[1]/following::a[1]</value>
      <webElementGuid>8efea7c5-60e5-4aae-a301-4d45ae27cfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more about driving and delivering'])[1]/following::a[1]</value>
      <webElementGuid>17c678fc-13c6-433b-85fd-3132dcc608ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Uber you know, reimagined for business'])[1]/preceding::a[1]</value>
      <webElementGuid>afc63a34-9eab-46ed-b66e-32d49cd80f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get started'])[2]/preceding::a[1]</value>
      <webElementGuid>a92767ee-f73b-4cd3-9d63-87a79906a97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get started']/parent::*</value>
      <webElementGuid>d9f2e38d-6fc1-4427-ac71-eba91e006730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.uber.com/in/en/drive/vehicle-solutions/fleet-partners/?uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957')]</value>
      <webElementGuid>4795d68f-80b6-407c-bc28-a2a09ad47c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/a</value>
      <webElementGuid>2b424cbe-db0c-4c78-aeb5-6a2d23fe7e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.uber.com/in/en/drive/vehicle-solutions/fleet-partners/?uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957' and (text() = 'Get started ' or . = 'Get started ') and @type = 'button']</value>
      <webElementGuid>01c90fa4-4361-4988-bc0c-5d55bcba2d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
