<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Request now</name>
   <tag></tag>
   <elementGuidId>f28f3907-daa8-4ed6-b2b2-3f656690a34b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div/div/div/div/div/div[3]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-impRdV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e02b87f-cd10-4486-bda2-be96bbe17d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-baseweb</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b008139-9ce9-4b58-a4de-6e2b927dc8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://m.uber.com/looking?marketing_vistor_id=6041b043-27cf-4a15-a275-5376c563866e&amp;uclick_id=ba647fcc-a07a-43b5-bbfd-ddc071482caf</value>
      <webElementGuid>8b40f11a-88c7-4971-9c88-4a43d631ea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Request now</value>
      <webElementGuid>12e7d980-8b76-4602-aff5-716984b4b3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-name</name>
      <type>Main</type>
      <value>homepage_product-header_trip-selector.request-now_cta1</value>
      <webElementGuid>f189a775-a91d-4b8e-a228-dadd509e6d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request now</value>
      <webElementGuid>dd305633-14bf-43b5-a59e-31154acca131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-impRdV</value>
      <webElementGuid>92e7e957-119a-4823-9229-470d305b7f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uclick-id</name>
      <type>Main</type>
      <value>ba647fcc-a07a-43b5-bbfd-ddc071482caf</value>
      <webElementGuid>31dcfd8b-4557-4fb7-9c2b-c29760d9eeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-doLtUX&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-eTHFdK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-cHaEgw&quot;]/div[@class=&quot;css-jxCaGu&quot;]/div[@class=&quot;css-gsuTXe&quot;]/div[@class=&quot;css-iulhGS&quot;]/div[@class=&quot;css-gaoOZL&quot;]/div[@class=&quot;css-dGKXrw&quot;]/div[@class=&quot;css-kmDgkF&quot;]/a[@class=&quot;css-impRdV&quot;]</value>
      <webElementGuid>d7213270-7246-4950-8384-b76843d55593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div/div/div/div/div/div[3]/div/a</value>
      <webElementGuid>1863b1eb-4674-4ee6-93ca-d742c9165150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Request now')]</value>
      <webElementGuid>6480666e-4e00-4aba-9121-386488ae09f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request a ride now'])[1]/following::a[1]</value>
      <webElementGuid>637db468-6a10-4ca8-b23f-1663bfbf0e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent your fleet'])[1]/following::a[1]</value>
      <webElementGuid>d812a4be-9f71-40e9-9338-e2c98b59abcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule for later'])[1]/preceding::a[1]</value>
      <webElementGuid>b8a54f84-8edb-4deb-9e28-e162a8647faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get in the driver’s seat and get paid'])[1]/preceding::a[2]</value>
      <webElementGuid>dde2caad-35b6-42d5-928f-0da91730da2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request now']/parent::*</value>
      <webElementGuid>35aea9a3-c3d6-4dd0-9a78-bd1cbcd5cfef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m.uber.com/looking?marketing_vistor_id=6041b043-27cf-4a15-a275-5376c563866e&amp;uclick_id=ba647fcc-a07a-43b5-bbfd-ddc071482caf')]</value>
      <webElementGuid>26b17d04-be69-4c3d-a255-a9d680f8945b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>41ed2a3d-65ed-462c-8b99-d3fd11692883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m.uber.com/looking?marketing_vistor_id=6041b043-27cf-4a15-a275-5376c563866e&amp;uclick_id=ba647fcc-a07a-43b5-bbfd-ddc071482caf' and (text() = 'Request now' or . = 'Request now')]</value>
      <webElementGuid>d260590e-a905-472a-8b91-4f5c68d8dc9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
