<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Request a ride now</name>
   <tag></tag>
   <elementGuidId>59b96a69-f467-44b5-840b-c618218ba945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.css-jzIGNN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/section/div/div/div/div/div[2]/div/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>7f7a4439-b63f-473f-831b-5c3b147b8bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-jzIGNN</value>
      <webElementGuid>c56e608c-b59f-42f8-9fed-c6bbf2b046a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request a ride now</value>
      <webElementGuid>2017d5ed-60a9-43cb-ad9c-96c19ddbe7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-doLtUX&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-hAZQJK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-cHaEgw&quot;]/div[@class=&quot;css-iulhGS&quot;]/div[@class=&quot;css-gaoOZL&quot;]/div[@class=&quot;css-hPnljU&quot;]/h2[@class=&quot;css-jzIGNN&quot;]</value>
      <webElementGuid>4a46c1f0-8025-44ca-812c-a419dbf43e53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div/div/div/div[2]/div/div/div/div/h2</value>
      <webElementGuid>9380a0e6-baa9-424f-940b-4f74adbd780c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent your fleet'])[1]/following::h2[1]</value>
      <webElementGuid>9953d4fb-1afe-455d-b9cf-6d289ec79f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drive or deliver'])[1]/following::h2[1]</value>
      <webElementGuid>380da2e0-9228-43a3-abe2-f2547bb3260a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request now'])[1]/preceding::h2[1]</value>
      <webElementGuid>e7a1bdad-78a0-4bc1-a1d8-d97e451a7f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule for later'])[1]/preceding::h2[1]</value>
      <webElementGuid>5bf11931-41ec-446f-b17e-a9a7d4c6a010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request a ride now']/parent::*</value>
      <webElementGuid>d56fe9f3-261b-4129-b7d0-aae55b1cce2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>9f5c793c-c8a2-4ef5-bb49-6f615a59a1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Request a ride now' or . = 'Request a ride now')]</value>
      <webElementGuid>3e1e90bf-f859-4f7a-aa50-f8500d3de176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
