<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Drive or deliver_css-iTMoEO</name>
   <tag></tag>
   <elementGuidId>dd92edfc-8a6c-43e7-869a-58477362cec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='2']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2 > div.css-bnRVZX > div.css-PKJb > div.css-zKsHo > img.css-iTMoEO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ecb2e16-e1f8-4c08-bd2d-d8c8df36ec3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.uber-assets.com/image/upload/v1674075480/assets/27/7a50c1-0782-405e-947c-83a2f4d78137/original/keys_car_filled.svg</value>
      <webElementGuid>69b5efd9-383f-4f4d-8533-89c7ebbb78d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>key-car-filled-icon</value>
      <webElementGuid>8346b3cd-de46-4cf5-874b-3f52732a17c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e14b5492-5fc9-4d28-8c4d-a4ad7ce9b0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f998cbfb-2778-40d3-981e-c53cef86fb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-iTMoEO</value>
      <webElementGuid>be294889-e252-4497-ae32-dd8d22089dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/div[@class=&quot;css-bnRVZX&quot;]/div[@class=&quot;css-PKJb&quot;]/div[@class=&quot;css-zKsHo&quot;]/img[@class=&quot;css-iTMoEO&quot;]</value>
      <webElementGuid>e7d5194e-51b5-48e7-937f-6ce8700d0bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='2']/div/div/div/img</value>
      <webElementGuid>b825c73b-6374-4f55-af3d-df3faf60dfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='key-car-filled-icon']</value>
      <webElementGuid>3abf70c3-a0c2-45e0-bc9e-54427e77ed03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div/div/div/img</value>
      <webElementGuid>8eb86381-8b63-444d-9ed4-a294bef80014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.uber-assets.com/image/upload/v1674075480/assets/27/7a50c1-0782-405e-947c-83a2f4d78137/original/keys_car_filled.svg' and @alt = 'key-car-filled-icon']</value>
      <webElementGuid>44b54dfd-5e80-444e-9109-bb97fb012f3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
