<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Request a ride now_destination_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>b24d6ec3-b841-4730-856f-50475c534e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='destination']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;destination&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56f99e49-78b7-45c0-8ddc-8ac56b1b0241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>0f92b247-0006-4cea-b634-5166e38585a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Airpor</value>
      <webElementGuid>cd82bd9b-4496-4a3c-90c2-70b1fa04e3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Where to?</value>
      <webElementGuid>4587f3de-f79f-4dc3-b506-e7ed9f6dd1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter destination</value>
      <webElementGuid>520860f3-154f-4bb4-a0d0-10acc7cbd49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>75db702e-cbf5-4932-b5c8-4b7d835cec52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>049a9a5b-4cc1-47e1-a2e1-2dcadeb8aa8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>ddfe5102-0f04-4ee7-856f-f1b41f707923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>destination-suggestions-listbox-0.17591129326107113</value>
      <webElementGuid>af72a9ab-9daa-44d0-aa0b-ad11a8bd06af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3d11ab2-8631-48b0-9bb4-618ee8c3f1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kDPYnB</value>
      <webElementGuid>dae0d853-80ab-49e1-8037-253bce42b00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Airpor</value>
      <webElementGuid>22660afe-8503-4c73-b99b-956e91db65d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-doLtUX&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-eTHFdK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-cHaEgw&quot;]/div[@class=&quot;css-jxCaGu&quot;]/div[@class=&quot;css-gsuTXe&quot;]/div[@class=&quot;css-iulhGS&quot;]/div[@class=&quot;css-gaoOZL&quot;]/div[@class=&quot;css-bwbuAu&quot;]/div[@class=&quot;css-TbLiS&quot;]/div[@class=&quot;css-cdQODT&quot;]/input[@class=&quot;css-kDPYnB&quot;]</value>
      <webElementGuid>c7d40a2b-43f8-4b56-9d5f-54a5d8d7aa64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='destination']</value>
      <webElementGuid>2ec632e4-c543-4402-9e60-938d60690583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>5f0864e1-43b8-42d1-83d0-19d2cf83b93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>d3393a83-d0f3-4fae-adac-8f6cd94c60e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'destination' and @title = 'Airpor' and @placeholder = 'Enter destination' and @type = 'text']</value>
      <webElementGuid>47ed58b9-5176-4780-ad62-21da49e6fa4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
