<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Request a ride now_pickup_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>6148db0f-46da-44d1-997f-2ac6d7395962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pickup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pickup&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa8b949d-4e0e-4981-a602-dce18fa99c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickup</value>
      <webElementGuid>32ccdc5d-024a-4e3b-ae13-40be24df5f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rail</value>
      <webElementGuid>19b7c570-bd1f-4431-b945-66456d3360a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter a pickup location: address, city and state required</value>
      <webElementGuid>168fb0db-21a4-48e8-974a-b886c4f08ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter pickup location</value>
      <webElementGuid>6670250c-b455-4c85-8f1c-fcc62fd91ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>12dfb435-1e4c-4774-a5ae-2ffa92d099ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>efb03bd8-624c-4cf7-95c9-c35c515fc92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c026cf61-9ad9-4456-ae0d-c6b1a4a1b8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pickup-suggestions-listbox-0.5747963641613651</value>
      <webElementGuid>00ce23b5-efee-461b-8706-e9b407725fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94e61e89-d8cd-4ee6-a81e-79634017300a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kDPYnB</value>
      <webElementGuid>b124afca-81bc-4ad2-9d80-120a96176930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rail</value>
      <webElementGuid>49391a2c-39e8-41d8-bcd3-4edc6c996d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-doLtUX&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-eTHFdK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-cHaEgw&quot;]/div[@class=&quot;css-jxCaGu&quot;]/div[@class=&quot;css-gsuTXe&quot;]/div[@class=&quot;css-iulhGS&quot;]/div[@class=&quot;css-gaoOZL&quot;]/div[@class=&quot;css-bwbuAu&quot;]/div[@class=&quot;css-gizoBm&quot;]/input[@class=&quot;css-kDPYnB&quot;]</value>
      <webElementGuid>db1a8bef-40ea-4b96-9aa5-721d1f25c802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pickup']</value>
      <webElementGuid>a1be4d72-1cc9-4531-8423-fd50e4131269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>05ec52db-a43f-479a-876a-1aee250eb6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0c2d970b-5e7e-46d3-828f-414b21ff18d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pickup' and @title = 'Rail' and @placeholder = 'Enter pickup location' and @type = 'text']</value>
      <webElementGuid>809d5f86-a1ca-4ae4-89a5-531516aa1fab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
