<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Request a ride now_destination</name>
   <tag></tag>
   <elementGuidId>da4dc7a0-3fc1-4b81-8ec1-c6e737654c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='destination']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;destination&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4ffc774-ae7a-40ea-9ab2-01fa7eb43d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>133d2e01-31a3-4c09-9c21-6a544810836c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Where to?</value>
      <webElementGuid>d246bf8a-d1e6-44b4-985a-5d84f72b1405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter destination</value>
      <webElementGuid>1fef9d72-3903-4dd5-8f3b-ddb2548d3825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>93264d8a-3c0d-4eda-a671-7ba16ef633fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89c60a4b-8158-405d-99b7-545729bf9e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>a80b32e6-b8a9-45b3-8b73-cfc891cdf87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>destination-suggestions-listbox-0.17591129326107113</value>
      <webElementGuid>2a7c25de-2083-47bc-8ab5-6b7bda4a0bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>99f4ff22-506b-4f1e-a639-655a5f948565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kDPYnB</value>
      <webElementGuid>f3d40719-b9e6-415b-8e1d-8c91ad7e88bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-doLtUX&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-eTHFdK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-cHaEgw&quot;]/div[@class=&quot;css-jxCaGu&quot;]/div[@class=&quot;css-gsuTXe&quot;]/div[@class=&quot;css-iulhGS&quot;]/div[@class=&quot;css-gaoOZL&quot;]/div[@class=&quot;css-bwbuAu&quot;]/div[@class=&quot;css-TbLiS&quot;]/div[@class=&quot;css-cdQODT&quot;]/input[@class=&quot;css-kDPYnB&quot;]</value>
      <webElementGuid>37fabc63-c03b-4714-b990-6cb72464d6de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='destination']</value>
      <webElementGuid>35f7ae29-c03d-4748-a1b1-801550b980db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>d8b98d75-9281-4e8f-a15c-c516af66e258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>bbf281c8-aac3-498e-afb6-ac232a20a22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'destination' and @placeholder = 'Enter destination' and @type = 'text']</value>
      <webElementGuid>89fbe391-b2cc-4606-a5c1-d7e275773be9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
