<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Request a ride now_pickup_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>2471016c-53e4-4154-bd6a-9bfed475dacc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pickup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pickup&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a23a25e-582b-482c-a0b7-2d37d7fe9031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickup</value>
      <webElementGuid>4ecfd55b-e848-4f1d-81ff-0917de2e7491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Railwayst</value>
      <webElementGuid>eaa7add2-b7d9-45cb-afcf-26d20508785c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter a pickup location: address, city and state required</value>
      <webElementGuid>b856ded5-7e92-4de8-b9e7-fa0fd4a85900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter pickup location</value>
      <webElementGuid>9b3a9e6b-9fed-4796-a406-45fb027c09c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a39649a3-55b8-44f5-a11c-8d897bd2823d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92443098-76c8-4aaf-a887-977d0e2ab928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>09e46f43-4d5b-4b3d-b533-e04742a7b91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pickup-suggestions-listbox-0.5747963641613651</value>
      <webElementGuid>624ac14d-4905-4331-8711-4837f2e84979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>226dda79-7d3e-4d3a-b167-7332111f860a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kDPYnB</value>
      <webElementGuid>1ee83ab6-3056-4e50-b780-2d994f2efab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Railwayst</value>
      <webElementGuid>385bdf97-de76-400d-976b-e9996d7b07c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-doLtUX&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-eTHFdK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-cHaEgw&quot;]/div[@class=&quot;css-jxCaGu&quot;]/div[@class=&quot;css-gsuTXe&quot;]/div[@class=&quot;css-iulhGS&quot;]/div[@class=&quot;css-gaoOZL&quot;]/div[@class=&quot;css-bwbuAu&quot;]/div[@class=&quot;css-gizoBm&quot;]/input[@class=&quot;css-kDPYnB&quot;]</value>
      <webElementGuid>b974e59b-2e5e-40f2-bc63-c9dbe3c57e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pickup']</value>
      <webElementGuid>f350f74c-7606-4a05-ae84-799788776201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>96cdea9c-dbc9-4083-89fb-c38bc0c826c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c14d1df7-e321-4ade-9ef6-1bb6e2fcd1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pickup' and @title = 'Railwayst' and @placeholder = 'Enter pickup location' and @type = 'text']</value>
      <webElementGuid>a16a5a91-93f0-4790-be2c-249fb23f7a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
