<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Request a ride now_destination_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>e2cd4944-9b7d-4c16-9553-82fdd8928d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='destination']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;destination&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48d734ee-5877-4062-9897-89d6394e5712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>294bce99-7f04-4086-8403-f36181179c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Airpo</value>
      <webElementGuid>b4df47a8-8db5-47ed-9165-34a12088c921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Where to?</value>
      <webElementGuid>e511fd37-9e06-4562-81b7-ce97bfdffee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter destination</value>
      <webElementGuid>9089225e-2c11-412f-bc61-edf080530bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc1753da-b199-4829-9378-fad98597cb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f5bb5d9-1094-4c68-b681-cdf8dcfc93b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>a1df0ad4-6f03-4c5b-8865-e4099bb8fe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>destination-suggestions-listbox-0.17591129326107113</value>
      <webElementGuid>d0f6a7d9-8fea-4091-a517-5c7e72da4b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52edb6ab-591e-4b08-ab19-65f867ed8505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kDPYnB</value>
      <webElementGuid>ebfa83a9-50e2-4f10-97fe-c18902589498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Airpo</value>
      <webElementGuid>39b8b77c-6cb5-4a6d-8391-a61508eef916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-kdBOxy&quot;]/section[@class=&quot;css-doLtUX&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-ofGld&quot;]/div[@class=&quot;container-inner css-eTHFdK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-haFmDf&quot;]/div[@class=&quot;css-cHaEgw&quot;]/div[@class=&quot;css-jxCaGu&quot;]/div[@class=&quot;css-gsuTXe&quot;]/div[@class=&quot;css-iulhGS&quot;]/div[@class=&quot;css-gaoOZL&quot;]/div[@class=&quot;css-bwbuAu&quot;]/div[@class=&quot;css-TbLiS&quot;]/div[@class=&quot;css-cdQODT&quot;]/input[@class=&quot;css-kDPYnB&quot;]</value>
      <webElementGuid>78d2938a-14b9-4428-85bd-2b58063893c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='destination']</value>
      <webElementGuid>425a4ab0-d712-4eb0-b9ee-443dc0fd042e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>3bacd605-dc5e-4d31-a9bc-e1590fc0d688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>9b36d3cd-3724-4be9-a410-03e457b31bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'destination' and @title = 'Airpo' and @placeholder = 'Enter destination' and @type = 'text']</value>
      <webElementGuid>fd8fb9c2-e910-445a-a2fe-a60fd69ad87d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
