<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Firefox Browsers</name>
   <tag></tag>
   <elementGuidId>48030afa-8cff-40e9-a672-fe6b363c8fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.c-menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-navigation-items']/div[2]/nav/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b2dba59-cadd-4e69-90d1-93adda34d72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-menu-title</value>
      <webElementGuid>be371350-3ee1-4c29-a0ae-6f4e0d100244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/firefox/browsers/</value>
      <webElementGuid>0d05eeaf-7b58-4bf4-ba16-6b146455e97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e07626c-de6a-4b05-8eed-0a3841f3b8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>c-menu-panel-firefox</value>
      <webElementGuid>ca991116-234c-4899-89f2-61f847a3410e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e43500f-4e45-40af-b963-e39b92ce61ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Firefox Browsers</value>
      <webElementGuid>5604c890-00df-4346-93c1-6285e1252922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-navigation-items&quot;)/div[@class=&quot;c-navigation-menu&quot;]/nav[@class=&quot;c-menu mzp-is-enhanced&quot;]/ul[@class=&quot;c-menu-category-list&quot;]/li[@class=&quot;c-menu-category mzp-has-drop-down mzp-js-expandable mzp-is-animated mzp-is-selected&quot;]/a[@class=&quot;c-menu-title&quot;]</value>
      <webElementGuid>bb9fb503-8af5-431a-8e46-3a4577d75241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-navigation-items']/div[2]/nav/ul/li/a</value>
      <webElementGuid>cb235e83-661c-47c8-8ef1-8be680dedf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Firefox Browsers')]</value>
      <webElementGuid>5ed1201d-617b-4e60-8323-3ddbb3f4b6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Mozilla VPN'])[1]/following::a[1]</value>
      <webElementGuid>0d99b76f-c9ca-4af8-bba9-9cd7a52d3baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefox Privacy Notice'])[1]/following::a[2]</value>
      <webElementGuid>7b48d8f0-c6ef-4133-8109-429d756a1799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Firefox Browsers menu'])[1]/preceding::a[1]</value>
      <webElementGuid>eb19204e-0511-4033-87ff-3ffb3755c335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefox for Desktop'])[1]/preceding::a[1]</value>
      <webElementGuid>8efac099-b662-40fd-93c8-5451c865e26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Firefox Browsers']/parent::*</value>
      <webElementGuid>fc38fe47-b63d-4d9f-8c65-64377efbce88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-US/firefox/browsers/')]</value>
      <webElementGuid>b672e9f7-1dcc-41bc-add8-68ad3c8a6a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>b557bbd3-ff02-40d2-8fa7-49dfd8a9568c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-US/firefox/browsers/' and (text() = 'Firefox Browsers' or . = 'Firefox Browsers')]</value>
      <webElementGuid>7f4e2703-2749-4a16-b4f2-0962ee1bc476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
