<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Firefox Browsers</name>
   <tag></tag>
   <elementGuidId>48030afa-8cff-40e9-a672-fe6b363c8fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.c-menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-navigation-items']/div[2]/nav/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48632295-5377-440e-a321-1c328b69bd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-menu-title</value>
      <webElementGuid>5702264b-df74-49a9-9509-e29c846b7b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/firefox/browsers/</value>
      <webElementGuid>b3e7b546-9db9-4407-b844-1de8415ea7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>319378c1-bcf5-41eb-9741-a830f88acb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>c-menu-panel-firefox</value>
      <webElementGuid>e428cc85-2eaa-4699-b086-26fe555cbf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b78b9d7-c2ca-4121-9fe0-2ee940d95ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Firefox Browsers</value>
      <webElementGuid>e6761d45-9ef2-4f13-acce-b64eea9b5f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-navigation-items&quot;)/div[@class=&quot;c-navigation-menu&quot;]/nav[@class=&quot;c-menu mzp-is-enhanced&quot;]/ul[@class=&quot;c-menu-category-list&quot;]/li[@class=&quot;c-menu-category mzp-has-drop-down mzp-js-expandable mzp-is-animated mzp-is-selected&quot;]/a[@class=&quot;c-menu-title&quot;]</value>
      <webElementGuid>d839b2e8-7264-40fe-a308-015ec89d4051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-navigation-items']/div[2]/nav/ul/li/a</value>
      <webElementGuid>f60a9e26-51ac-4977-b566-a9063c5503c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Firefox Browsers')]</value>
      <webElementGuid>868fbb12-5828-4ae7-8542-2a5e682fb272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Mozilla VPN'])[1]/following::a[1]</value>
      <webElementGuid>f1c15951-d60c-4f36-b24f-394c4a5f163f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefox Privacy Notice'])[1]/following::a[2]</value>
      <webElementGuid>4af12d9c-ff0a-46a2-aac8-abc28ea71217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Firefox Browsers menu'])[1]/preceding::a[1]</value>
      <webElementGuid>f68e70cd-ff67-445b-8893-53ae69854be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefox for Desktop'])[1]/preceding::a[1]</value>
      <webElementGuid>30ca7385-e17d-43e3-a5eb-af1df0293749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Firefox Browsers']/parent::*</value>
      <webElementGuid>1c5baff4-6ae8-4c4c-9ca2-ef319872877a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-US/firefox/browsers/')]</value>
      <webElementGuid>1985ad93-7690-4a1c-af6c-a377655c55e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>ba1ea95f-18dd-4975-8669-e3539347b3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-US/firefox/browsers/' and (text() = 'Firefox Browsers' or . = 'Firefox Browsers')]</value>
      <webElementGuid>d76d6419-11ad-4192-86d8-01eaf9b2ba61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
