<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Book Now</name>
   <tag></tag>
   <elementGuidId>cc47843b-c869-4643-8172-374fcba31f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='teaser-e8a434cc1e-cta-95b806f958']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#teaser-e8a434cc1e-cta-95b806f958</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f57c4c15-83a9-4df2-aee8-a1e88b6a87a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-teaser__action-link</value>
      <webElementGuid>97e60740-debc-4ee2-9a4e-ce766f1a7557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teaser-e8a434cc1e-cta-95b806f958</value>
      <webElementGuid>5573b4f2-2e6d-422f-a248-78af5a386e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cmp-data-layer</name>
      <type>Main</type>
      <value>{&quot;teaser-e8a434cc1e-cta-95b806f958&quot;:{&quot;@type&quot;:&quot;ecom/components/cheerios/teaser/v1/teaser/cta&quot;,&quot;dc:title&quot;:&quot;Book Now&quot;,&quot;xdm:linkURL&quot;:&quot;/en/car-rental/deals/10off-base-weekly-airport.html&quot;}}</value>
      <webElementGuid>447d5a94-dcef-400f-915e-6d543e00e509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/car-rental/deals/10off-base-weekly-airport.html</value>
      <webElementGuid>5b953192-2dd7-44cc-8d88-e4da269ed0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Now</value>
      <webElementGuid>27770d35-b268-40e3-a78d-9d08fdf59d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teaser-e8a434cc1e-cta-95b806f958&quot;)</value>
      <webElementGuid>4b7a1c11-fbcf-4b23-a96f-cf32b7cd29b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='teaser-e8a434cc1e-cta-95b806f958']</value>
      <webElementGuid>c43acbe3-4d74-4fce-b260-daff88f6534d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='teaser-e8a434cc1e']/div[2]/div[2]/a</value>
      <webElementGuid>c8e64ae9-f2fc-4cc0-97e8-7b0aa8bebd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Book Now')]</value>
      <webElementGuid>6a9bd3a1-149e-48ed-8ede-a21bf73073ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save on Airport Weekly Rentals'])[1]/following::a[1]</value>
      <webElementGuid>d9635167-0497-41b1-a771-eb7e366ce498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured Deals'])[1]/following::a[1]</value>
      <webElementGuid>1e72dce0-96a0-4df9-a9de-554dfcddbffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save on Airport Weekend Rentals'])[1]/preceding::a[1]</value>
      <webElementGuid>ea761375-3bee-47d3-9c69-65fa8b5ee7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Now'])[2]/preceding::a[1]</value>
      <webElementGuid>ac1968c0-e899-49b5-886b-5e5591b1a84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book Now']/parent::*</value>
      <webElementGuid>dbb461ce-5ad0-42d4-9b77-3636612cc0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/car-rental/deals/10off-base-weekly-airport.html')]</value>
      <webElementGuid>a9ca69bc-f168-4f1c-8fc9-0b8b37727516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>69637d86-a667-4dc3-9d4e-767d22d400d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'teaser-e8a434cc1e-cta-95b806f958' and @href = '/en/car-rental/deals/10off-base-weekly-airport.html' and (text() = 'Book Now' or . = 'Book Now')]</value>
      <webElementGuid>4bec8c19-de14-43e0-a4d0-d803d26f2477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
