<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Become a Seller</name>
   <tag></tag>
   <elementGuidId>5e9d18a3-a824-4274-bdb0-0ff152b13bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._1krdK5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div/header/div[2]/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>215abe25-d95d-44b2-ad31-75ed2657d998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1krdK5</value>
      <webElementGuid>8c5683ba-328f-40d5-8871-f8e1ebc16bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://seller.flipkart.com/sell-online/?utm_source=fkwebsite&amp;utm_medium=websitedirect</value>
      <webElementGuid>ce48ddd3-2a62-47d4-bbb3-5149d9d7346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Become a Seller</value>
      <webElementGuid>c6960878-169b-4831-afee-14ce65b20534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Become a Seller</value>
      <webElementGuid>377e7187-70c3-4c58-a3b5-16a837090520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;q8WwEU&quot;]/div[@class=&quot;_3zsGrb&quot;]/div[@class=&quot;_2-LWwB&quot;]/div[1]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;_1ui5b4&quot;]/div[@class=&quot;_2NhoPJ&quot;]/header[@class=&quot;_3EOQ5Q&quot;]/div[@class=&quot;_2msBFL&quot;]/div[1]/div[@class=&quot;_38VF5e&quot;]/a[@class=&quot;_1krdK5&quot;]</value>
      <webElementGuid>e0d9fb1a-1c8d-4687-bc17-3f7f27696dc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div/header/div[2]/div/div/a[2]</value>
      <webElementGuid>34a7753d-4430-4173-84b5-9026707920fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Become a Seller')]</value>
      <webElementGuid>b92d295f-4dff-4f76-a8f8-89c8c7342e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plus'])[1]/following::a[2]</value>
      <webElementGuid>35e0d420-2a8d-4f29-b15b-bc3008e66ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/following::a[2]</value>
      <webElementGuid>bb071e1f-a2af-4909-94b9-49eb84703dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>13f8e1e8-282c-4709-857f-06925ae92aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New customer?'])[1]/preceding::a[2]</value>
      <webElementGuid>0cee252d-aad3-4d02-886e-7118d643c91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Become a Seller']/parent::*</value>
      <webElementGuid>4afa91d3-5bc9-4674-89a1-e48e93df0246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://seller.flipkart.com/sell-online/?utm_source=fkwebsite&amp;utm_medium=websitedirect')])[2]</value>
      <webElementGuid>47fd9d2c-b8b0-4190-be81-e857da769af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]</value>
      <webElementGuid>fdc29578-5351-49ca-a2f4-855699a781b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://seller.flipkart.com/sell-online/?utm_source=fkwebsite&amp;utm_medium=websitedirect' and @title = 'Become a Seller' and (text() = 'Become a Seller' or . = 'Become a Seller')]</value>
      <webElementGuid>d7314b4b-f9b6-4a61-b88a-3dba3214f2e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
