<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign up now</name>
   <tag></tag>
   <elementGuidId>3f771b7b-4271-46f9-bcb2-8d5f2e9598d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/section/div/div[2]/div/div/div/div/div[3]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-bENDJs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e4b59c3-5ad2-46b5-97f4-bd58c9f84c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-baseweb</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e3c3f67-5900-499a-8151-93aa5534beff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://drivers.uber.com/?marketing_vistor_id=c555f38b-24c9-4495-9386-45120262adab&amp;uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957</value>
      <webElementGuid>40d27bd3-8857-4578-bdea-c52c9b1f6262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up now</value>
      <webElementGuid>8657f07a-df8a-43f5-ad31-d341880ff83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-name</name>
      <type>Main</type>
      <value>join_1160711b-30c3-41bd-876c-5a1d2972f4db_ctaOne.ctaDetails_cta1</value>
      <webElementGuid>2f7ae1f4-22c3-4384-83b6-cefed15badfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-bENDJs</value>
      <webElementGuid>62b4b5f1-4fa7-4b3d-8f81-3b38381d2cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uclick-id</name>
      <type>Main</type>
      <value>94d95b38-3e58-4cf5-8ed6-d3df3e6cb957</value>
      <webElementGuid>6c277159-3ec7-4791-a010-738a7f753d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;css-PKJb&quot;]/section[@class=&quot;css-ktNNbE&quot;]/div[@class=&quot;css-hazmlH&quot;]/div[@class=&quot;css-emwIIr&quot;]/div[@class=&quot;container-inner css-dwgaGO&quot;]/div[@class=&quot;css-bVFrLX&quot;]/div[@class=&quot;css-iFQotK&quot;]/div[@class=&quot;css-cYTjpz&quot;]/div[@class=&quot;css-PKJb&quot;]/div[@class=&quot;css-WiLSj&quot;]/div[@class=&quot;css-iYgZzq&quot;]/a[@class=&quot;css-bENDJs&quot;]</value>
      <webElementGuid>593f3d87-0925-4c5f-b28a-248d35f3d4bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/section/div/div[2]/div/div/div/div/div[3]/div/div/a</value>
      <webElementGuid>e4f0c31a-7d93-45b8-bb2c-aeae9c9c9e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up now')]</value>
      <webElementGuid>fdc59e34-66f7-4b8a-964c-61d0ef609b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drive with Uber'])[1]/following::a[1]</value>
      <webElementGuid>ef93ab68-52d9-4fde-b467-b4d63a8eb358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have an account?'])[1]/following::a[1]</value>
      <webElementGuid>7a55b1c1-62e3-4613-a30f-809faad836fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already have an account? Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>4c465195-d9ed-4c8a-b47c-80cd6c5ac581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drive when you want'])[1]/preceding::a[2]</value>
      <webElementGuid>7936ebb9-22c1-4a2c-8a02-13fd8b0276a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up now']/parent::*</value>
      <webElementGuid>b4ea4858-d8ac-46ba-aaf9-b1c1fcb2f8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://drivers.uber.com/?marketing_vistor_id=c555f38b-24c9-4495-9386-45120262adab&amp;uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957')]</value>
      <webElementGuid>e13e4311-854f-4c01-848c-037db21c3b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>80827a7e-01d4-48ed-aee7-d8926d568c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://drivers.uber.com/?marketing_vistor_id=c555f38b-24c9-4495-9386-45120262adab&amp;uclick_id=94d95b38-3e58-4cf5-8ed6-d3df3e6cb957' and (text() = 'Sign up now' or . = 'Sign up now')]</value>
      <webElementGuid>526c430a-f1ec-4d95-9da5-4383ceeeb481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
