<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign up</name>
   <tag></tag>
   <elementGuidId>1ad3f830-dae7-4cfe-a97f-11ddd9ab24b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='signin-menu']/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.signups</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1fb4d17-da51-4785-aa4e-51a8e12606fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://login.yahoo.com/account/create?.src=ym&amp;pspid=1197806870&amp;activity=header-signup&amp;.lang=en-US&amp;.intl=us&amp;.done=https%3A%2F%2Fmail.yahoo.com%2Fd&amp;authMechanism=primary&amp;specId=yidReg</value>
      <webElementGuid>d4543d14-0c42-47b6-add9-864a8aa112b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signups</value>
      <webElementGuid>b44ab80e-e795-4e9d-b61a-f58baa9d92fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>mKey:signup_click</value>
      <webElementGuid>a5f2c72e-554c-4692-ae0a-ce1cb7bf5c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>024409d4-b5dd-4438-8c28-deaff7d5df8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>90fb309e-7d59-466d-bec0-67c4cdf3fee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>942ea2d8-b882-425d-ad56-dcd067f82818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-menu&quot;)/li[4]/a[@class=&quot;signups&quot;]</value>
      <webElementGuid>f9ef4ce7-ed07-40f9-ad14-1a8f1901efce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='signin-menu']/li[4]/a</value>
      <webElementGuid>c5bb1d14-c175-4efd-99bb-c897cb2bdf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up')]</value>
      <webElementGuid>f92f0093-49d6-40d2-b122-523e75aebefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/following::a[1]</value>
      <webElementGuid>7fa81d93-53bc-45d2-8f07-4120087ff0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade to Mail Plus'])[1]/following::a[2]</value>
      <webElementGuid>2dd3843e-9908-4e09-84f4-f4aaeb5711b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Stuff'])[1]/preceding::a[1]</value>
      <webElementGuid>0947c816-8d77-4d87-8c39-b76c146f625b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::a[1]</value>
      <webElementGuid>4d656567-775e-44d9-b0a0-d1151f1b27db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up']/parent::*</value>
      <webElementGuid>b38912e0-c567-4d15-94ac-0d98f2692300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://login.yahoo.com/account/create?.src=ym&amp;pspid=1197806870&amp;activity=header-signup&amp;.lang=en-US&amp;.intl=us&amp;.done=https%3A%2F%2Fmail.yahoo.com%2Fd&amp;authMechanism=primary&amp;specId=yidReg')]</value>
      <webElementGuid>8c2bd6fb-e0b9-4a1b-86e4-a5f4abc9e993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>a1f2da62-933c-4d37-a24a-0244c5670b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://login.yahoo.com/account/create?.src=ym&amp;pspid=1197806870&amp;activity=header-signup&amp;.lang=en-US&amp;.intl=us&amp;.done=https%3A%2F%2Fmail.yahoo.com%2Fd&amp;authMechanism=primary&amp;specId=yidReg' and @alt = 'Sign up' and (text() = 'Sign up' or . = 'Sign up')]</value>
      <webElementGuid>abb538bf-0a64-4000-9491-34e64bc6b99c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
