<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Images</name>
   <tag></tag>
   <elementGuidId>4dc5ec54-fd87-405b-9c67-0879eea4dac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bqHHPb']/div/div/div/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.FMKtTb.UqcIvb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>600f3be3-fb33-476b-927d-43fb9e26860f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FMKtTb UqcIvb</value>
      <webElementGuid>5e179d04-e58e-4284-96fb-710eaae78a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>pIvPIe</value>
      <webElementGuid>7dd4ca04-88ad-4140-b623-e80e49742032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Images</value>
      <webElementGuid>b1bf8913-7a06-4dcc-a146-7dc0c971cea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bqHHPb&quot;)/div[@class=&quot;fMHynf Jb8vdb&quot;]/div[1]/div[@class=&quot;IUOThf&quot;]/a[@class=&quot;LatpMc nPDzT T3FoJb&quot;]/div[@class=&quot;GKS7s&quot;]/span[@class=&quot;FMKtTb UqcIvb&quot;]</value>
      <webElementGuid>16952012-b22d-479c-8082-2eb44f5a9e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bqHHPb']/div/div/div/a/div/span</value>
      <webElementGuid>d52ba53f-a71e-40cf-8294-f2c30145904e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters and topics'])[1]/following::span[1]</value>
      <webElementGuid>bfbbef8f-3119-4276-b12d-fd7920223d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::span[2]</value>
      <webElementGuid>15e2c707-bdfd-447e-ab9f-9e7bfc2348c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/preceding::span[1]</value>
      <webElementGuid>e75d7e3d-bb9f-4594-a21e-a4e164301e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lifespan'])[1]/preceding::span[2]</value>
      <webElementGuid>b8ea943e-8fd7-46ba-bae1-9618c2578351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Images']/parent::*</value>
      <webElementGuid>69f69a0b-e0bd-45e2-9142-e0216d932e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span</value>
      <webElementGuid>cd688607-15c8-48ab-90bd-7993b7e3e52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Images' or . = 'Images')]</value>
      <webElementGuid>320c93f9-7b21-4f62-b496-4fbc66b0530d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
