<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_Gaming</name>
   <tag></tag>
   <elementGuidId>281cf8d7-b12e-45f6-bade-3aaed2d348e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>2ac91d67-c079-4612-aeb8-ba100f8056f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df9a2f52-dfc7-4e03-846e-77b0a09ad810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope yt-chip-cloud-chip-renderer</value>
      <webElementGuid>070715ee-88dc-4081-8c07-66fa94bdb1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Gaming</value>
      <webElementGuid>ded1c942-a043-404a-93db-30a9c28ec113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gaming</value>
      <webElementGuid>885939f3-cd48-462a-9b72-9c174c52a4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chips&quot;)/yt-chip-cloud-chip-renderer[@class=&quot;style-scope ytd-feed-filter-chip-bar-renderer&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>6766dfb7-6561-430c-bb8f-72920c9524bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='text'])[2]</value>
      <webElementGuid>5c5e2d27-ba02-4674-9e26-e32b7f2b734c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-selector[@id='chips']/yt-chip-cloud-chip-renderer[2]/yt-formatted-string</value>
      <webElementGuid>f12d3c6f-d3b6-49bb-89d4-2fb6c1baaa71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>f9871dc1-ce7a-4622-9ca7-ca293be917a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Music'])[1]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>fc17e498-c801-4919-a3c8-0699aaefacd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live'])[1]/preceding::yt-formatted-string[2]</value>
      <webElementGuid>1eefd54d-0920-4e43-9208-6b5244ec7342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gaming']/parent::*</value>
      <webElementGuid>1467a25d-c2b2-4b0b-8066-0ec116b70158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//yt-chip-cloud-chip-renderer[2]/yt-formatted-string</value>
      <webElementGuid>ad5bd6e3-1b13-47e1-aec2-a452d3e8b154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and @title = 'Gaming' and (text() = 'Gaming' or . = 'Gaming')]</value>
      <webElementGuid>bb098379-37f7-48bc-9baa-9a839bad96f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
