<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Current Deals_cmp-teaser__action-link--overlay</name>
   <tag></tag>
   <elementGuidId>10ce6823-2ff7-467c-a5a6-c6a5e694e3c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='teaser-f5be089907']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9ff458e-a8db-4168-bad5-e711d5f31f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-teaser__action-link--overlay </value>
      <webElementGuid>37543934-7875-4a18-b4d8-33157c9c1909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icid</name>
      <type>Main</type>
      <value>teaser_copy-_-Deals &amp; Promotions-_-deals</value>
      <webElementGuid>7aa2101e-fcb0-42e2-b580-2dc7f476f481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/car-rental/deals.html</value>
      <webElementGuid>cedf3537-706d-40ca-b24e-309b4247a1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teaser-f5be089907&quot;)/a[@class=&quot;cmp-teaser__action-link--overlay&quot;]</value>
      <webElementGuid>61984107-7f32-47e5-b600-e55a933336d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='teaser-f5be089907']/a</value>
      <webElementGuid>35016762-a38f-4f46-b6a6-172b5c618c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Deals'])[1]/following::a[1]</value>
      <webElementGuid>5580537d-4e1b-4bf7-bc36-d17a15b8bd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotions'])[1]/following::a[2]</value>
      <webElementGuid>7fe8e9ad-2769-4ee5-a001-828fcc3adf89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Kind of Travel Planning'])[1]/preceding::a[1]</value>
      <webElementGuid>b86e7207-6a87-4266-a825-814e7adb2fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Plus® Program'])[3]/preceding::a[3]</value>
      <webElementGuid>b54920a9-d433-4b15-b0c5-3d3a005e3379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/car-rental/deals.html')])[4]</value>
      <webElementGuid>d0a36225-2cef-4705-97c7-1ccb434e8c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>b773f611-ca7c-409a-a583-0d4a6f6ef67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/car-rental/deals.html']</value>
      <webElementGuid>8d32af92-8a16-44e0-a91a-0b0d901a9e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
