<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Select</name>
   <tag></tag>
   <elementGuidId>54817ef1-5a3f-433c-b638-e1abdadbdeb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='location-1018781']/small</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>small.location-group__item-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>d258fb03-ba34-403e-962e-51aab7bdce59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>location-group__item-select</value>
      <webElementGuid>67806f82-3f53-4119-a047-caf591def6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>d7c8a2a9-9797-4686-8971-e27ecd05afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location-1018781&quot;)/small[@class=&quot;location-group__item-select&quot;]</value>
      <webElementGuid>61eee9a7-74e1-43b1-960f-a7ebabd0b978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='location-1018781']/small</value>
      <webElementGuid>cf6ddbbe-2c46-4231-bdd2-fc11be1eb461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JFK'])[2]/following::small[1]</value>
      <webElementGuid>0c5a4663-ddb0-4f57-bcf3-4bcde7481952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JFK'])[3]/preceding::small[1]</value>
      <webElementGuid>8c03d0a2-843e-46ad-a8ab-4261eb1e44b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>949b89ff-05b4-4216-a733-6d22665e9c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/small</value>
      <webElementGuid>581a27ed-d6f3-47c1-8fd3-beca54a7248f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>c247a2db-5c77-4072-9359-6a6bea882dcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
